import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
path = 'C:/Users/carlo/Desktop/CIUdades/Trabajo-final-Ciudades-inteligentes/Ciudades-TrabajoFinal.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

idx29 = next(i for i, c in enumerate(nb['cells']) if c.get('id') == 'e42d5366')
idx30 = next(i for i, c in enumerate(nb['cells']) if c.get('id') == '1c6d7423')
idx31 = next(i for i, c in enumerate(nb['cells']) if c.get('id') == '075a8386')
print(f'idx29={idx29}  idx30={idx30}  idx31={idx31}')

cell_29_lines = [
    "from gpytorch.kernels import MaternKernel, LinearKernel\n",
    "torch.manual_seed(0)\n",
    "\n",
    "# ── Paso 1: carga y promediado semanal de O3 en MY1 ────────────────────────\n",
    "# Los datos horarios (2019-2022) se colapsan a 52 valores/año mediando por semana.\n",
    "def load_o3_weekly(station='MY1'):\n",
    "    df = pd.read_csv(f'{DATA_DIR}/raw/laqn/{station}/no2_pm25_o3_2019_2024.csv')\n",
    "    df['ReadingDateTime'] = pd.to_datetime(df['ReadingDateTime'], dayfirst=True)\n",
    "    o3 = df[df['Species'] == 'O3'].set_index('ReadingDateTime')['Value']\n",
    "    o3 = o3[~o3.index.duplicated(keep='first')].sort_index()\n",
    "    o3 = o3[o3.index.year < 2023]          # mismo corte que en el EDA\n",
    "    return o3.resample('W').mean().dropna()\n",
    "\n",
    "o3_weekly = load_o3_weekly()\n",
    "print(f'O3 semanal (MY1, 2019-2022): {len(o3_weekly)} semanas')\n",
    "print(o3_weekly.describe().round(2))\n",
    "\n",
    "# ── Paso 2: reorganización autoregresiva AR(k) ──────────────────────────────\n",
    "# Entrada: (x(t-1), x(t-2), ..., x(t-k))  → Salida: x(t)\n",
    "k = 8   # 8 semanas de historial (~2 meses)\n",
    "\n",
    "def crear_secuencias_ar(serie, k):\n",
    "    vals = serie.values.astype(np.float32)\n",
    "    X, y, fechas = [], [], []\n",
    "    for i in range(k, len(vals)):\n",
    "        X.append(vals[i-k:i])\n",
    "        y.append(vals[i])\n",
    "        fechas.append(serie.index[i])\n",
    "    return np.array(X, np.float32), np.array(y, np.float32), pd.DatetimeIndex(fechas)\n",
    "\n",
    "X_all, y_all, dates_all = crear_secuencias_ar(o3_weekly, k)\n",
    "\n",
    "# ── Paso 3: división train (2019-2021) / test (2022) ────────────────────────\n",
    "mask_tr = dates_all.year <= 2021\n",
    "mask_te = dates_all.year == 2022\n",
    "\n",
    "X_tr, y_tr, dates_tr = X_all[mask_tr], y_all[mask_tr], dates_all[mask_tr]\n",
    "X_te, y_te, dates_te = X_all[mask_te], y_all[mask_te], dates_all[mask_te]\n",
    "print(f'Train: {len(y_tr)} semanas | Test: {len(y_te)} semanas')\n",
    "\n",
    "# ── Paso 4: estandarización con estadísticos del train ──────────────────────\n",
    "scaler_x = StandardScaler().fit(X_tr)\n",
    "scaler_y = StandardScaler().fit(y_tr.reshape(-1, 1))\n",
    "mu_y = float(scaler_y.mean_[0]); sd_y = float(scaler_y.scale_[0])\n",
    "\n",
    "def sx(A):  return scaler_x.transform(A).astype(np.float32)\n",
    "def sy(a):  return ((a - mu_y) / sd_y).astype(np.float32)\n",
    "def isy(a): return a * sd_y + mu_y\n",
    "\n",
    "X_tr_s = sx(X_tr); y_tr_s = sy(y_tr)\n",
    "X_te_s = sx(X_te)\n",
    "X_tr_t = torch.from_numpy(X_tr_s)\n",
    "y_tr_t = torch.from_numpy(y_tr_s)\n",
    "\n",
    "# ── Paso 5: diseño del kernel ────────────────────────────────────────────────\n",
    "# Se parte de un kernel lineal (captura tendencia) y se aumenta la complejidad\n",
    "# añadiendo un Matern-5/2 (suavidad local) para capturar variación no lineal.\n",
    "# Kernel final: ScaleKernel(LinearKernel + MaternKernel(nu=2.5))\n",
    "class ARGP(ExactGP):\n",
    "    def __init__(self, X, y, lik):\n",
    "        super().__init__(X, y, lik)\n",
    "        self.mean_module  = ConstantMean()\n",
    "        self.covar_module = ScaleKernel(\n",
    "            LinearKernel()          # tendencia lineal\n",
    "            + MaternKernel(nu=2.5)  # variacion local suave\n",
    "        )\n",
    "    def forward(self, x):\n",
    "        return MultivariateNormal(self.mean_module(x), self.covar_module(x))\n",
    "\n",
    "# Ruido Gaussiano homocedástico (piso de ruido para evitar interpolación exacta)\n",
    "likelihood = GaussianLikelihood(\n",
    "    noise_constraint=gpytorch.constraints.GreaterThan(1e-3)\n",
    ")\n",
    "model = ARGP(X_tr_t, y_tr_t, likelihood)\n",
    "\n",
    "# ── Paso 6: entrenamiento con GPyTorch ──────────────────────────────────────\n",
    "model.train(); likelihood.train()\n",
    "optimizer = torch.optim.Adam(model.parameters(), lr=0.05)\n",
    "mll       = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)\n",
    "\n",
    "EPOCHS = 300\n",
    "for epoch in range(EPOCHS):\n",
    "    optimizer.zero_grad()\n",
    "    loss = -mll(model(X_tr_t), y_tr_t)\n",
    "    loss.backward(); optimizer.step()\n",
    "    if epoch == 200:\n",
    "        for g in optimizer.param_groups: g['lr'] = 0.01\n",
    "    if (epoch + 1) % 60 == 0:\n",
    "        print(f'Epoch {epoch+1:3d}/{EPOCHS}  MLL-loss = {loss.item():.4f}')\n",
    "\n",
    "print('Entrenamiento del GP completado.')\n",
]

cell_30_lines = [
    "model.eval(); likelihood.eval()\n",
    "\n",
    "def gp_pred(X_np):\n",
    "    Xt = torch.from_numpy(X_np.astype(np.float32))\n",
    "    with torch.no_grad(), gpytorch.settings.fast_pred_var():\n",
    "        dist = likelihood(model(Xt))\n",
    "    return isy(dist.mean.numpy()), dist.stddev.numpy() * sd_y\n",
    "\n",
    "mu_tr, sig_tr = gp_pred(X_tr_s)\n",
    "mu_te, sig_te = gp_pred(X_te_s)\n",
    "\n",
    "# Métricas\n",
    "def metrics(yt, yp):\n",
    "    return {'R2':   r2_score(yt, yp),\n",
    "            'MAE':  mean_absolute_error(yt, yp),\n",
    "            'RMSE': float(np.sqrt(mean_squared_error(yt, yp)))}\n",
    "\n",
    "m_tr = metrics(y_tr, mu_tr)\n",
    "m_te = metrics(y_te, mu_te)\n",
    "\n",
    "print(f'{\"Split\":<6} {\"R2\":>8} {\"MAE\":>8} {\"RMSE\":>8}')\n",
    "print('-' * 34)\n",
    "print(f'{\"Train\":<6} {m_tr[\"R2\"]:>8.3f} {m_tr[\"MAE\"]:>8.2f} {m_tr[\"RMSE\"]:>8.2f}')\n",
    "print(f'{\"Test\":<6} {m_te[\"R2\"]:>8.3f} {m_te[\"MAE\"]:>8.2f} {m_te[\"RMSE\"]:>8.2f}')\n",
    "\n",
    "if m_te['R2'] > 0.7:\n",
    "    print(f'\\n✓ R² test = {m_te[\"R2\"]:.3f} satisface el requisito R² > 0.7')\n",
    "else:\n",
    "    print(f'\\n⚠ R² test = {m_te[\"R2\"]:.3f} (objetivo > 0.7)')\n",
    "\n",
    "# Paso 8: % de muestras de test dentro del IC ±1σ\n",
    "within_1s = np.mean((y_te >= mu_te - sig_te) & (y_te <= mu_te + sig_te)) * 100\n",
    "print(f'Muestras de test dentro de ±1σ: {within_1s:.1f}%  (esperado ≈68% ruido gaussiano)')\n",
    "\n",
    "# ── Paso 7: gráfico predicción vs. observaciones en test con IC ±1σ ──────────\n",
    "fig, axes = plt.subplots(2, 1, figsize=(13, 8), gridspec_kw={'height_ratios': [2, 1]})\n",
    "\n",
    "# Panel superior — serie completa (train + test)\n",
    "ax = axes[0]\n",
    "ax.plot(o3_weekly.index, o3_weekly.values,\n",
    "        color='#888', lw=0.8, alpha=0.6, label='O₃ semanal real')\n",
    "ax.plot(dates_tr, mu_tr, color='#2a7db5', lw=1.4, label='Predicción GP – train')\n",
    "ax.plot(dates_te, mu_te, color='#c65f46', lw=1.8, label='Predicción GP – test')\n",
    "ax.fill_between(dates_te, mu_te - sig_te, mu_te + sig_te,\n",
    "                color='#c65f46', alpha=0.25, label='IC ±1σ (test)')\n",
    "ax.axvspan(dates_te[0], dates_te[-1], color='#fde8e0', alpha=0.35)\n",
    "ax.set_title('Predicción de O₃ semanal (MY1) — Proceso Gaussiano AR(k=8)',\n",
    "             fontweight='bold')\n",
    "ax.set_ylabel('O₃ (μg/m³)'); ax.legend(fontsize=8); ax.grid(alpha=0.25)\n",
    "ymax = ax.get_ylim()[1]\n",
    "ax.text(dates_tr[len(dates_tr)//2], ymax*0.93, 'TRAIN (2019-2021)',\n",
    "        ha='center', fontsize=9, color='#2a7db5', fontweight='bold')\n",
    "ax.text(dates_te[len(dates_te)//2], ymax*0.93, 'TEST (2022)',\n",
    "        ha='center', fontsize=9, color='#c65f46', fontweight='bold')\n",
    "\n",
    "# Panel inferior — solo periodo de test con IC ±1σ\n",
    "ax2 = axes[1]\n",
    "ax2.plot(dates_te, y_te,  color='#333', lw=1.2, marker='o', ms=3, label='Observado')\n",
    "ax2.plot(dates_te, mu_te, color='#c65f46', lw=1.8, label='Predicho (μ)')\n",
    "ax2.fill_between(dates_te, mu_te - sig_te, mu_te + sig_te,\n",
    "                 color='#c65f46', alpha=0.30, label='IC ±1σ')\n",
    "ax2.set_title(\n",
    "    f'Test 2022 — R²={m_te[\"R2\"]:.3f}  MAE={m_te[\"MAE\"]:.1f} μg/m³  '\n",
    "    f'{within_1s:.0f}% de muestras dentro de ±1σ',\n",
    "    fontweight='bold')\n",
    "ax2.set_xlabel('Semana'); ax2.set_ylabel('O₃ (μg/m³)')\n",
    "ax2.legend(fontsize=8); ax2.grid(alpha=0.25)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig(f'{DASH_DIR}/img/fig_gp_no2.png', bbox_inches='tight', dpi=160)\n",
    "plt.show()\n",
]

# Cell 31: dashboard block — build the HTML as a concatenated string in Python
cell_31_lines = [
    "tabla_html = (\n",
    "    '<tr><td>Train 2019-2021</td>'\n",
    "    f'<td>{m_tr[\"R2\"]:.3f}</td><td>{m_tr[\"MAE\"]:.2f}</td><td>{m_tr[\"RMSE\"]:.2f}</td></tr>'\n",
    "    '<tr><td>Test 2022</td>'\n",
    "    f'<td>{m_te[\"R2\"]:.3f}</td><td>{m_te[\"MAE\"]:.2f}</td><td>{m_te[\"RMSE\"]:.2f}</td></tr>'\n",
    ")\n",
    "\n",
    "DASH_BLOCKS['modelo'] = (\n",
    "    '<div class=\"img-grid\">'\n",
    "    '  <div class=\"img-card\">'\n",
    "    '    <img src=\"img/fig_gp_no2.png\"/>'\n",
    "    f'    <p>Predicción GP de O₃ semanal (MY1, 2022) — IC ±1σ. '\n",
    "    f'{within_1s:.0f}% de muestras test dentro del intervalo.</p>'\n",
    "    '  </div>'\n",
    "    '</div>'\n",
    "    '<table class=\"data-table\">'\n",
    "    '  <thead><tr><th>Split</th><th>R²</th><th>MAE (μg/m³)</th><th>RMSE (μg/m³)</th></tr></thead>'\n",
    "    f'  <tbody>{tabla_html}</tbody>'\n",
    "    '</table>'\n",
    "    '<p style=\"margin-top:1rem;color:#555;font-size:.88rem\">'\n",
    "    'Modelo: <code>ExactGP</code> autoregresivo AR(k=8) sobre O₃ semanal de MY1 (Marylebone Rd).<br>'\n",
    "    'Kernel: <code>ScaleKernel(LinearKernel + MaternKernel(ν=2.5))</code> — ruido Gaussiano homocedástico.<br>'\n",
    "    'Estandarización ajustada solo con el split de entrenamiento.'\n",
    "    '</p>'\n",
    ")\n",
    "print('Dashboard actualizado:', render_dashboard())\n",
]

for idx, lines in [(idx29, cell_29_lines), (idx30, cell_30_lines), (idx31, cell_31_lines)]:
    nb['cells'][idx]['source'] = lines
    nb['cells'][idx]['outputs'] = []
    nb['cells'][idx]['execution_count'] = None

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print('Cells 29/30/31 rewritten successfully.')
